# This file contains the essential steps for getting the app packaged and scanned using Veracode's various
# scan types.  We suggest starting with the elements in this file and fully understanding them before
# attempting more advanced use cases, like 'Pipeline scan on a PR', or importing Issues.

# The essential steps shown below are:
#   checkout and package the app for scanning
#   upload for a static scan
#   run the SCA agent scan
#   run the Container scan

name: the-essentials

on:
  workflow_dispatch:

jobs:
  checkout-and-package:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with: 
          node-version: '20.14.0'

      - name: Zip app files
        run: | 
          rm -rf verademo-python.zip
          zip -r verademo-python.zip .

      - name: save artifact
        uses: actions/upload-artifact@v3
        with: 
           name: scan-target
           path: verademo-python.zip
           
# Steps above are the bare minimum.
# Here below there are additional steps that are commonplace
  sca-scan: 
    needs: checkout-and-package
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'

      - name: debug1
        run: | 
          pwd 
          ls -l

      - name: do SCA scan
        env: 
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: veracode/veracode-sca@v2.1.12
        with:
          path: ./
          create-issues: false

      - name: display SCA results
        run: |
          cat scaResults.txt

  
      
  
  

    
